/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface User {
  avatar: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  password: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  user: User;
}
